DECIMALS_IN_CURRENCY = 100
ID_MAIN_LEVEL_IN_MAIN_MENU = '1'
NOT_FOUND_EMPLOYEE = -1
CASH_SHIFT_EXPENSE_ID = 3
CASH_SHIFT_NOT_DELETED = 0
SECONDS_IN_HOURS = 3600
SECONDS_IN_MINUTES = 60
MAIN_MENU = {0: 'Головний екран'}  # Основное меню в Postere
